name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
      - staging
      - main

env:
  PROJECT_CI: keycloak-mnhm
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_DRIVER: overlay2
  RECOLNAT_VERSION: 1.0.0
  APP_VERSION: ""
  RECOLNAT_REGISTRY: dfgxr43v.c1.gra9.container-registry.ovh.net

jobs:
  build-and-publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - name: prod
            branch: main
            tag: prod
          - name: preprod
            branch: staging
            tag: rc
          - name: test
            branch: develop
            tag: test 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: |
          export APP_VERSION="origin"
          mvn $MAVEN_CLI_OPTS -Drevision=$APP_VERSION clean install -f ./pom.xml

      - name: Log in to Docker registry
        if: github.ref_name == matrix.environment.branch
        run: docker login ${{ env.RECOLNAT_REGISTRY }} -u 'robot$recolnat-ci' -p ${{ secrets.HARBOR_REGISTRY_PASSWORD }}

      - name: Build Docker image
        if: github.ref_name == matrix.environment.branch
        run: |
          export APP_VERSION="${{ matrix.environment.tag }}"
          docker build -t ${{ env.RECOLNAT_REGISTRY }}/recolnat/keycloak:${{ matrix.environment.tag }} -f Dockerfile .

      - name: Push Docker image
        if: github.ref_name == matrix.environment.branch
        run: docker push ${{ env.RECOLNAT_REGISTRY }}/recolnat/keycloak:${{ matrix.environment.tag }}